server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  redis:
    host: localhost
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
auth:
  exclude-path-patterns: /swagger-resources/**,/v2/api-docs/**
